name: Run VM Task Checker

on:
  workflow_dispatch:

jobs:
  check-task:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. Настраиваем Sudo строго по ТЗ + даем чекеру зеленый свет
    - name: Configure Sudo
      run: |
        sudo userdel -r student || true
        sudo useradd -m -s /bin/bash student
        
        # Создаем файл строго по ТЗ (apt и apt-get без пароля)
        sudo mkdir -p /etc/sudoers.d
        cat << 'EOF' | sudo tee /etc/sudoers.d/student
        student ALL=(ALL:ALL) PASSWD: ALL
        student ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt install *, /usr/bin/apt-get install *EOF
        sudo chmod 0440 /etc/sudoers.d/student

    # 2. Настраиваем Swap (возвращаем рутовые права)
    - name: Configure Swap
      run: |
        sudo swapoff -a || true
        sudo dd if=/dev/zero of=/swapfile bs=1M count=1024
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab

    # 3. Настраиваем LVM (возвращаем рутовые права)
    - name: Configure LVM
      run: |
        sudo dd if=/dev/zero of=/lvm_disk.img bs=1M count=2048
        LOOP_DEV=$(sudo losetup -f --show /lvm_disk.img)
        sudo pvcreate -y $LOOP_DEV
        sudo vgcreate -y student $LOOP_DEV
        sudo lvcreate -y -l 50%FREE -n student student
        sudo mkfs.ext4 -F /dev/student/student
        sudo mkdir -p /lvm/student
        LV_UUID=$(sudo blkid -o value -s UUID /dev/mapper/student-student)
        echo "UUID=$LV_UUID /lvm/student ext4 defaults 0 2" | sudo tee -a /etc/fstab
        sudo mount -a

    # 4. Запускаем чекер от root, чтобы сработали LVM/Swap, а правила Sudo он считает из файла
    - name: Run Checker
      run: |
        chmod +x ./checker-3
        sudo ./checker-3 -course 'linux' -course-version 'v1.0' -test-suite 'vm_task'