name: Run VM Task Checker

on:
  workflow_dispatch:

jobs:
  check-task:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. Точная настройка Sudo Rights по ТЗ
    - name: Configure Sudo
      run: |
        # Удаляем старого пользователя, если он остался, создаем начисто и задаем пароль 'student'
        sudo userdel -r student || true
        sudo useradd -m -s /bin/bash student
        echo "student:student" | sudo chpasswd
        
        # Добавляем в группу sudo, чтобы остальные команды запрашивали пароль
        sudo usermod -aG sudo student
        
        # Создаем конфигурационный файл в sudoers.d по правилам ТЗ:
        # Разрешаем конкретные команды БЕЗ пароля
        sudo mkdir -p /etc/sudoers.d
        echo "student ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt install *, /usr/bin/apt-get install *" | sudo tee /etc/sudoers.d/student
        sudo chmod 0440 /etc/sudoers.d/student

    # 2. Настраиваем Swap
    - name: Configure Swap
      run: |
        sudo swapoff -a || true
        sudo dd if=/dev/zero of=/swapfile bs=1M count=1024
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab

    # 3. Настраиваем LVM
    - name: Configure LVM
      run: |
        sudo dd if=/dev/zero of=/lvm_disk.img bs=1M count=2048
        LOOP_DEV=$(sudo losetup -f --show /lvm_disk.img)
        sudo pvcreate -y $LOOP_DEV
        sudo vgcreate -y student $LOOP_DEV
        sudo lvcreate -y -l 50%FREE -n student student
        sudo mkfs.ext4 -F /dev/student/student
        sudo mkdir -p /lvm/student
        LV_UUID=$(sudo blkid -o value -s UUID /dev/mapper/student-student)
        echo "UUID=$LV_UUID /lvm/student ext4 defaults 0 2" | sudo tee -a /etc/fstab
        sudo mount -a

    # 4. Запуск оригинального чекера из-под пользователя student
    - name: Run Checker
      run: |
        chmod +x ./checker-3
        chmod 777 ./
        sudo -u student ./checker-3 -course 'linux' -course-version 'v1.0' -test-suite 'vm_task'